### ISSUE TITLE
Can not access the project.

### ISSUE THREAD

**Issue by yuetong3yu** [ospic/webapp#949]
**Describe the bug**
I would like to checkout the HMS, but can not access the web page.
I think its server-side CORS problem.

Also, I had try to clone the project to my local, and the npm installation also failed.

**To Reproduce**
1. node version, v16.6.2
2. npm install

**Screenshots**
![image](https://user-images.githubusercontent.com/48756922/132278894-681576e9-4a10-4c64-9015-d4ac779d131b.png)
![image](https://user-images.githubusercontent.com/48756922/132279485-cd3ab01a-b46b-4570-8c82-4776a3f87f02.png)

**Comment by elirehema** [comment]
Hello, @yuetong3yu we have been working busily to implement multi-tenant platform and so the server environment is not working fine for now. We will get in touch with you as soon as we resolve this

**Comment by yuetong3yu** [comment]
@elirehema Glad to see your reply. Hope you everything is great.

**Comment by elirehema** [comment]
@yuetong3yu Yeah everything is okay. Just working hard for Saas platform

**Comment by elirehema** [comment]
Hi, @yuetong3yu we have managed to configure the previous platform to work in another database. You can access it from this link https://ospic.github.io/webapp/#/ . API's documentation can still be found in heroku https://ospicapi.herokuapp.com/api/swagger-ui.html

You may experience slowness in data retrieval and display it is because of the free database from db4free which has limited bandwidth.

We have also managed to implement the SAAS platform in which most of the developments now will be moved to this new platform. This version will be moved to live server as soon as we as assured that everything is fine. Thanks for your concern

**Comment by yuetong3yu** [comment]
@elirehema Impressive! Thank you~

**Comment by elirehema** [comment]
@yuetong3yu can I close this issue now?

**Comment by yuetong3yu** [comment]
@elirehema it works fine for me, thx for your work.
